/*
* generated by Xtext
*/
package org.openhab.model.rule;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RulesUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.openhab.model.rule.ui.internal.RulesActivator.getInstance().getInjector("org.openhab.model.rule.Rules");
	}
	
}
