/*
* generated by Xtext
*/
package org.openhab.model.script;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ScriptUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.openhab.model.script.ui.internal.ScriptActivator.getInstance().getInjector("org.openhab.model.script.Script");
	}
	
}
